name: zoomies
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14
  - pip
  - pip:
    - python-dotenv
    - discord.py
    - aiohttp
    - python-dateutil
    - sqlalchemy>=2.0.0
    - alembic
    - psycopg2-binary
    